cache:
  directories:
    - $HOME/.ivy2/cache

language: scala

scala:
  - 2.10.6

jdk:
  - oraclejdk7
  - openjdk7

notifications:
  email: true

script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dsbt.log.noformat=true gen-tmpl
  - sbt ++$TRAVIS_SCALA_VERSION -Dsbt.log.noformat=true compile
  - sbt ++$TRAVIS_SCALA_VERSION -Dsbt.log.noformat=true test
